window.esdocSearchIndex = [
  [
    "better-xlsx/src/style.js~alignment",
    "class/src/style.js~Alignment.html",
    "<span>Alignment</span> <span class=\"search-result-import-path\">better-xlsx/src/style.js</span>",
    "class"
  ],
  [
    "better-xlsx/src/style.js~border",
    "class/src/style.js~Border.html",
    "<span>Border</span> <span class=\"search-result-import-path\">better-xlsx/src/style.js</span>",
    "class"
  ],
  [
    "better-xlsx/src/cell.js~cell",
    "class/src/cell.js~Cell.html",
    "<span>Cell</span> <span class=\"search-result-import-path\">better-xlsx/src/cell.js</span>",
    "class"
  ],
  [
    "better-xlsx/src/col.js~col",
    "class/src/col.js~Col.html",
    "<span>Col</span> <span class=\"search-result-import-path\">better-xlsx/src/col.js</span>",
    "class"
  ],
  [
    "better-xlsx/src/file.js~file",
    "class/src/file.js~File.html",
    "<span>File</span> <span class=\"search-result-import-path\">better-xlsx/src/file.js</span>",
    "class"
  ],
  [
    "better-xlsx/src/style.js~fill",
    "class/src/style.js~Fill.html",
    "<span>Fill</span> <span class=\"search-result-import-path\">better-xlsx/src/style.js</span>",
    "class"
  ],
  [
    "better-xlsx/src/style.js~font",
    "class/src/style.js~Font.html",
    "<span>Font</span> <span class=\"search-result-import-path\">better-xlsx/src/style.js</span>",
    "class"
  ],
  [
    "better-xlsx/src/lib.js~numfmt",
    "variable/index.html#static-variable-NumFmt",
    "<span>NumFmt</span> <span class=\"search-result-import-path\">better-xlsx/src/lib.js</span>",
    "variable"
  ],
  [
    "better-xlsx/src/row.js~row",
    "class/src/row.js~Row.html",
    "<span>Row</span> <span class=\"search-result-import-path\">better-xlsx/src/row.js</span>",
    "class"
  ],
  [
    "better-xlsx/src/sheet.js~sheet",
    "class/src/sheet.js~Sheet.html",
    "<span>Sheet</span> <span class=\"search-result-import-path\">better-xlsx/src/sheet.js</span>",
    "class"
  ],
  [
    "better-xlsx/src/style.js~style",
    "class/src/style.js~Style.html",
    "<span>Style</span> <span class=\"search-result-import-path\">better-xlsx/src/style.js</span>",
    "class"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/cell.js",
    "file/src/cell.js.html",
    "src/cell.js",
    "file"
  ],
  [
    "src/cell.js~cell#constructor",
    "class/src/cell.js~Cell.html#instance-constructor-constructor",
    "src/cell.js~Cell#constructor",
    "method"
  ],
  [
    "src/cell.js~cell#hmerge",
    "class/src/cell.js~Cell.html#instance-member-hMerge",
    "src/cell.js~Cell#hMerge",
    "member"
  ],
  [
    "src/cell.js~cell#hidden",
    "class/src/cell.js~Cell.html#instance-member-hidden",
    "src/cell.js~Cell#hidden",
    "member"
  ],
  [
    "src/cell.js~cell#numfmt",
    "class/src/cell.js~Cell.html#instance-member-numFmt",
    "src/cell.js~Cell#numFmt",
    "member"
  ],
  [
    "src/cell.js~cell#setbool",
    "class/src/cell.js~Cell.html#instance-method-setBool",
    "src/cell.js~Cell#setBool",
    "method"
  ],
  [
    "src/cell.js~cell#setdate",
    "class/src/cell.js~Cell.html#instance-method-setDate",
    "src/cell.js~Cell#setDate",
    "method"
  ],
  [
    "src/cell.js~cell#setdatetime",
    "class/src/cell.js~Cell.html#instance-method-setDateTime",
    "src/cell.js~Cell#setDateTime",
    "method"
  ],
  [
    "src/cell.js~cell#setformula",
    "class/src/cell.js~Cell.html#instance-method-setFormula",
    "src/cell.js~Cell#setFormula",
    "method"
  ],
  [
    "src/cell.js~cell#setnumber",
    "class/src/cell.js~Cell.html#instance-method-setNumber",
    "src/cell.js~Cell#setNumber",
    "method"
  ],
  [
    "src/cell.js~cell#setstring",
    "class/src/cell.js~Cell.html#instance-method-setString",
    "src/cell.js~Cell#setString",
    "method"
  ],
  [
    "src/cell.js~cell#style",
    "class/src/cell.js~Cell.html#instance-set-style",
    "src/cell.js~Cell#style",
    "member"
  ],
  [
    "src/cell.js~cell#style",
    "class/src/cell.js~Cell.html#instance-get-style",
    "src/cell.js~Cell#style",
    "member"
  ],
  [
    "src/cell.js~cell#vmerge",
    "class/src/cell.js~Cell.html#instance-member-vMerge",
    "src/cell.js~Cell#vMerge",
    "member"
  ],
  [
    "src/cell.js~cell#value",
    "class/src/cell.js~Cell.html#instance-set-value",
    "src/cell.js~Cell#value",
    "member"
  ],
  [
    "src/cell.js~cell#value",
    "class/src/cell.js~Cell.html#instance-get-value",
    "src/cell.js~Cell#value",
    "member"
  ],
  [
    "src/col.js",
    "file/src/col.js.html",
    "src/col.js",
    "file"
  ],
  [
    "src/col.js~col#numfmt",
    "class/src/col.js~Col.html#instance-member-numFmt",
    "src/col.js~Col#numFmt",
    "member"
  ],
  [
    "src/col.js~col#style",
    "class/src/col.js~Col.html#instance-member-style",
    "src/col.js~Col#style",
    "member"
  ],
  [
    "src/col.js~col#width",
    "class/src/col.js~Col.html#instance-member-width",
    "src/col.js~Col#width",
    "member"
  ],
  [
    "src/file.js",
    "file/src/file.js.html",
    "src/file.js",
    "file"
  ],
  [
    "src/file.js~file#addsheet",
    "class/src/file.js~File.html#instance-method-addSheet",
    "src/file.js~File#addSheet",
    "method"
  ],
  [
    "src/file.js~file#definednames",
    "class/src/file.js~File.html#instance-member-definedNames",
    "src/file.js~File#definedNames",
    "member"
  ],
  [
    "src/file.js~file#makeparts",
    "class/src/file.js~File.html#instance-method-makeParts",
    "src/file.js~File#makeParts",
    "method"
  ],
  [
    "src/file.js~file#saveas",
    "class/src/file.js~File.html#instance-method-saveAs",
    "src/file.js~File#saveAs",
    "method"
  ],
  [
    "src/file.js~file#sheet",
    "class/src/file.js~File.html#instance-member-sheet",
    "src/file.js~File#sheet",
    "member"
  ],
  [
    "src/file.js~file#sheets",
    "class/src/file.js~File.html#instance-member-sheets",
    "src/file.js~File#sheets",
    "member"
  ],
  [
    "src/file.js~file#styles",
    "class/src/file.js~File.html#instance-member-styles",
    "src/file.js~File#styles",
    "member"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/lib.js",
    "file/src/lib.js.html",
    "src/lib.js",
    "file"
  ],
  [
    "src/node.js",
    "file/src/node.js.html",
    "src/node.js",
    "file"
  ],
  [
    "src/reftable.js",
    "file/src/reftable.js.html",
    "src/reftable.js",
    "file"
  ],
  [
    "src/row.js",
    "file/src/row.js.html",
    "src/row.js",
    "file"
  ],
  [
    "src/row.js~row#addcell",
    "class/src/row.js~Row.html#instance-method-addCell",
    "src/row.js~Row#addCell",
    "method"
  ],
  [
    "src/row.js~row#height",
    "class/src/row.js~Row.html#instance-member-height",
    "src/row.js~Row#height",
    "member"
  ],
  [
    "src/row.js~row#setheightcm",
    "class/src/row.js~Row.html#instance-method-setHeightCM",
    "src/row.js~Row#setHeightCM",
    "method"
  ],
  [
    "src/sheet.js",
    "file/src/sheet.js.html",
    "src/sheet.js",
    "file"
  ],
  [
    "src/sheet.js~sheet#addrow",
    "class/src/sheet.js~Sheet.html#instance-method-addRow",
    "src/sheet.js~Sheet#addRow",
    "method"
  ],
  [
    "src/sheet.js~sheet#cell",
    "class/src/sheet.js~Sheet.html#instance-method-cell",
    "src/sheet.js~Sheet#cell",
    "method"
  ],
  [
    "src/sheet.js~sheet#col",
    "class/src/sheet.js~Sheet.html#instance-method-col",
    "src/sheet.js~Sheet#col",
    "method"
  ],
  [
    "src/sheet.js~sheet#row",
    "class/src/sheet.js~Sheet.html#instance-method-row",
    "src/sheet.js~Sheet#row",
    "method"
  ],
  [
    "src/sheet.js~sheet#setcolwidth",
    "class/src/sheet.js~Sheet.html#instance-method-setColWidth",
    "src/sheet.js~Sheet#setColWidth",
    "method"
  ],
  [
    "src/style.js",
    "file/src/style.js.html",
    "src/style.js",
    "file"
  ],
  [
    "src/style.js~alignment#h",
    "class/src/style.js~Alignment.html#instance-member-h",
    "src/style.js~Alignment#h",
    "member"
  ],
  [
    "src/style.js~alignment#v",
    "class/src/style.js~Alignment.html#instance-member-v",
    "src/style.js~Alignment#v",
    "member"
  ],
  [
    "src/style.js~border#bottom",
    "class/src/style.js~Border.html#instance-member-bottom",
    "src/style.js~Border#bottom",
    "member"
  ],
  [
    "src/style.js~border#bottomcolor",
    "class/src/style.js~Border.html#instance-member-bottomColor",
    "src/style.js~Border#bottomColor",
    "member"
  ],
  [
    "src/style.js~border#left",
    "class/src/style.js~Border.html#instance-member-left",
    "src/style.js~Border#left",
    "member"
  ],
  [
    "src/style.js~border#leftcolor",
    "class/src/style.js~Border.html#instance-member-leftColor",
    "src/style.js~Border#leftColor",
    "member"
  ],
  [
    "src/style.js~border#right",
    "class/src/style.js~Border.html#instance-member-right",
    "src/style.js~Border#right",
    "member"
  ],
  [
    "src/style.js~border#rightcolor",
    "class/src/style.js~Border.html#instance-member-rightColor",
    "src/style.js~Border#rightColor",
    "member"
  ],
  [
    "src/style.js~border#top",
    "class/src/style.js~Border.html#instance-member-top",
    "src/style.js~Border#top",
    "member"
  ],
  [
    "src/style.js~border#topcolor",
    "class/src/style.js~Border.html#instance-member-topColor",
    "src/style.js~Border#topColor",
    "member"
  ],
  [
    "src/style.js~fill#bgcolor",
    "class/src/style.js~Fill.html#instance-member-bgColor",
    "src/style.js~Fill#bgColor",
    "member"
  ],
  [
    "src/style.js~fill#fgcolor",
    "class/src/style.js~Fill.html#instance-member-fgColor",
    "src/style.js~Fill#fgColor",
    "member"
  ],
  [
    "src/style.js~fill#patterntype",
    "class/src/style.js~Fill.html#instance-member-patternType",
    "src/style.js~Fill#patternType",
    "member"
  ],
  [
    "src/style.js~font#bold",
    "class/src/style.js~Font.html#instance-member-bold",
    "src/style.js~Font#bold",
    "member"
  ],
  [
    "src/style.js~font#color",
    "class/src/style.js~Font.html#instance-member-color",
    "src/style.js~Font#color",
    "member"
  ],
  [
    "src/style.js~font#italic",
    "class/src/style.js~Font.html#instance-member-italic",
    "src/style.js~Font#italic",
    "member"
  ],
  [
    "src/style.js~font#size",
    "class/src/style.js~Font.html#instance-member-size",
    "src/style.js~Font#size",
    "member"
  ],
  [
    "src/style.js~font#underline",
    "class/src/style.js~Font.html#instance-member-underline",
    "src/style.js~Font#underline",
    "member"
  ],
  [
    "src/style.js~style#align",
    "class/src/style.js~Style.html#instance-member-align",
    "src/style.js~Style#align",
    "member"
  ],
  [
    "src/style.js~style#border",
    "class/src/style.js~Style.html#instance-member-border",
    "src/style.js~Style#border",
    "member"
  ],
  [
    "src/style.js~style#fill",
    "class/src/style.js~Style.html#instance-member-fill",
    "src/style.js~Style#fill",
    "member"
  ],
  [
    "src/style.js~style#font",
    "class/src/style.js~Style.html#instance-member-font",
    "src/style.js~Style#font",
    "member"
  ],
  [
    "src/templates.js",
    "file/src/templates.js.html",
    "src/templates.js",
    "file"
  ]
]